"""empty message

Revision ID: 4ba662f61c3c
Revises: 
Create Date: 2023-08-15 14:01:45.841570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba662f61c3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.String(length=30), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('geolocation', sa.String(length=255), nullable=False),
    sa.Column('internet_speed', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schools')
    # ### end Alembic commands ###
